name: Ali Amin-Nejad
title: Ali Amin-Nejad's Blog
author: Ali Amin-Nejad
description: Machine Learning Engineer
github: http://www.github.com/amin-nejad
twitter: http://www.twitter.com/amin_nejad
linkedin: http://www.linkedin.com/in/ali-amin-nejad
email: ali[at]bitfount.com
location: London, UK
disqus: amin_nejad
layout: default
comments: true

permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-feed

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
