name: Ali Amin-Nejad
author: Ali Amin-Nejad
description: Data Scientist
baseurl: 
github: http://www.github.com/amin-nejad
twitter: http://www.twitter.com/amin_nejad
linkedin: http://www.linkedin.com/in/ali-amin-nejad
email: ali[at]bitfount.com
location: London, UK
disqus: amin_nejad
layout: default
comments: true


highlighter: pygments

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
