name: Ali Amin-Nejad
title: Ali Amin-Nejad
author: Ali Amin-Nejad
description: Machine Learning Engineer
baseurl: 
github: http://www.github.com/amin-nejad
twitter: http://www.twitter.com/amin_nejad
linkedin: http://www.linkedin.com/in/ali-amin-nejad
email: ali[at]bitfount.com
location: London, UK
disqus: amin_nejad
layout: default
comments: true

plugins:
    - jekyll-redirect-from

highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
